import { useNavigate } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

const TermsOfService = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-nixon-dark">
      <div className="px-6 py-4">
        <button
          onClick={() => navigate("/")}
          className="flex items-center gap-2 text-primary-foreground/70 hover:text-accent transition-colors text-sm font-body"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to Home
        </button>
      </div>

      <div className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="font-heading text-4xl text-primary-foreground mb-2">Terms of Service</h1>
        <p className="text-primary-foreground/50 font-body text-sm mb-10">
          Last updated: March 30, 2026
        </p>

        <div className="space-y-8 text-primary-foreground/80 font-body text-sm leading-relaxed">
          <section>
            <h2 className="font-heading text-xl text-primary-foreground mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using the Nixon Senior Living website ("Site"), operated by Nixon Home Care, Inc.,
              you agree to be bound by these Terms of Service. If you do not agree to these terms,
              please do not use the Site.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl text-primary-foreground mb-3">2. Use of the Site</h2>
            <p className="mb-3">You agree to use the Site only for lawful purposes. You may not:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Use the Site in any way that violates applicable laws or regulations</li>
              <li>Attempt to gain unauthorized access to any part of the Site or its systems</li>
              <li>Use the Site to transmit harmful, offensive, or misleading content</li>
              <li>Interfere with or disrupt the Site's functionality or security</li>
            </ul>
          </section>

          <section>
            <h2 className="font-heading text-xl text-primary-foreground mb-3">3. Intellectual Property</h2>
            <p>
              All content on the Site — including text, images, logos, graphics, and design — is the
              property of Nixon Home Care, Inc. and is protected by applicable intellectual property
              laws. You may not reproduce, distribute, or create derivative works without our prior
              written consent.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl text-primary-foreground mb-3">4. Resident Portal</h2>
            <p>
              Access to the Resident Portal is restricted to authorized residents and staff of Nixon
              Senior Living Estates. You are responsible for maintaining the confidentiality of your
              login credentials. You agree to notify us immediately of any unauthorized use of your account.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl text-primary-foreground mb-3">5. AI Chatbot</h2>
            <p>
              Our website features an AI-powered virtual assistant. While we strive for accuracy,
              responses are generated by artificial intelligence and may not always be complete or
              up to date. The chatbot is for informational purposes only and does not constitute
              professional advice. For official information, please contact us directly at (713) 419-2653.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl text-primary-foreground mb-3">6. Disclaimer of Warranties</h2>
            <p>
              The Site is provided "as is" and "as available" without warranties of any kind, either
              express or implied. Nixon Home Care, Inc. does not warrant that the Site will be
              uninterrupted, error-free, or free of harmful components.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl text-primary-foreground mb-3">7. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by law, Nixon Home Care, Inc. shall not be liable for
              any indirect, incidental, special, or consequential damages arising from your use of
              or inability to use the Site.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl text-primary-foreground mb-3">8. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms of Service at any time. Changes will be
              effective when posted on this page. Your continued use of the Site after changes
              constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl text-primary-foreground mb-3">9. Governing Law</h2>
            <p>
              These Terms are governed by and construed in accordance with the laws of the State of
              Texas, without regard to its conflict of law provisions.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl text-primary-foreground mb-3">10. Contact Us</h2>
            <p>If you have questions about these Terms, please contact us:</p>
            <div className="mt-3 bg-primary-foreground/5 border border-primary-foreground/10 rounded-lg p-4">
              <p className="text-primary-foreground font-heading">Nixon Home Care, Inc.</p>
              <p>Phone: (713) 419-2653</p>
              <p>Houston, TX Area</p>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
